version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      electron-forge:
        patterns:
          - "@electron-forge/*"
          - "@electron/*"
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - "@electron-forge/*"
          - "@electron/*"
          - "electron"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
